// AUTO-GENERATED by gen-assets.mjs from stage/assets/*.png — DO NOT EDIT.
pub struct Group{pub name:&'static str,pub frames:&'static [&'static [u8]]}
pub const GROUPS:&[Group]=&[
  Group{name:"chatbox",frames:&[include_bytes!("../assets/chatbox_0.png")]},
  Group{name:"excited",frames:&[include_bytes!("../assets/excited_0.png"),include_bytes!("../assets/excited_1.png"),include_bytes!("../assets/excited_2.png"),include_bytes!("../assets/excited_3.png"),include_bytes!("../assets/excited_4.png"),include_bytes!("../assets/excited_5.png"),include_bytes!("../assets/excited_6.png"),include_bytes!("../assets/excited_7.png")]},
  Group{name:"heart",frames:&[include_bytes!("../assets/heart_0.png"),include_bytes!("../assets/heart_1.png")]},
  Group{name:"idle",frames:&[include_bytes!("../assets/idle_0.png")]},
  Group{name:"jump",frames:&[include_bytes!("../assets/jump_0.png"),include_bytes!("../assets/jump_1.png")]},
  Group{name:"sleep",frames:&[include_bytes!("../assets/sleep_0.png"),include_bytes!("../assets/sleep_1.png"),include_bytes!("../assets/sleep_2.png"),include_bytes!("../assets/sleep_3.png")]},
  Group{name:"talk",frames:&[include_bytes!("../assets/talk_0.png"),include_bytes!("../assets/talk_1.png"),include_bytes!("../assets/talk_2.png")]},
  Group{name:"work",frames:&[include_bytes!("../assets/work_0.png"),include_bytes!("../assets/work_1.png"),include_bytes!("../assets/work_2.png"),include_bytes!("../assets/work_3.png"),include_bytes!("../assets/work_4.png"),include_bytes!("../assets/work_5.png"),include_bytes!("../assets/work_6.png"),include_bytes!("../assets/work_7.png"),include_bytes!("../assets/work_8.png"),include_bytes!("../assets/work_9.png")]},
  Group{name:"zzz",frames:&[include_bytes!("../assets/zzz_0.png"),include_bytes!("../assets/zzz_1.png"),include_bytes!("../assets/zzz_2.png")]},
];
