// AUTO-GENERATED by spec/codegen.mjs from spec/spec.ts — DO NOT EDIT.
// The `pi` surface, pinned. Codes are append-only (RUNTIMES.md).

#![allow(dead_code)]

pub const SURFACE: &str = "pi";
pub const VERSION: u32 = 1;
pub const DISPATCH: &str = "__pi_dispatch";

/// () => number — Wall clock, ms since epoch. Host-owned so deterministic hosts can fix it.
pub const OP_NOW: u32 = 1;
/// () => number — Monotonic ms since host start.
pub const OP_MONOTONIC: u32 = 2;
/// () => number — Host RNG in [0,1). Seedable for deterministic replays.
pub const OP_RANDOM: u32 = 3;
/// (id: number, ms: number) => void — Arm a one-shot timer; fires as a `timer` event. Guests never own timers (Law 3).
pub const OP_TIMER_START: u32 = 4;
/// (id: number) => void — Disarm a timer; already-fired ids are ignored.
pub const OP_TIMER_CLEAR: u32 = 5;
/// (id: number, req: string) => void — Begin an HTTP request. `req` is JSON {url, method?, headers?, body?}. Progress arrives as fetch* events; response bodies stream as text chunks (SSE-friendly; v1 is text-only).
pub const OP_FETCH_START: u32 = 6;
/// (id: number) => void — Abort an inflight request; a fetchError event with aborted=true follows.
pub const OP_FETCH_ABORT: u32 = 7;
/// (path: string) => string | null — Read a UTF-8 file under the sandbox root; null when absent.
pub const OP_FS_READ: u32 = 8;
/// (path: string, text: string) => void — Write (create/truncate) a UTF-8 file under the root, creating parents.
pub const OP_FS_WRITE: u32 = 9;
/// (path: string, text: string) => void — Append UTF-8 text under the root, creating parents. The event-log primitive.
pub const OP_FS_APPEND: u32 = 10;
/// (path: string) => boolean — Whether a path exists under the root.
pub const OP_FS_EXISTS: u32 = 11;
/// (path: string) => void — Remove a file under the root; missing is a no-op.
pub const OP_FS_REMOVE: u32 = 12;
/// (name: string) => string | null — Read an allowlisted environment value (--allow-env / --env at launch).
pub const OP_ENV: u32 = 13;
/// () => string — JSON array of guest argv (everything after the bundle path).
pub const OP_ARGS: u32 = 14;
/// (code: number) => void — Request host exit with a status code at the end of this turn.
pub const OP_EXIT: u32 = 15;

/// {id: number} — An armed timer elapsed.
pub const EV_TIMER: &str = "timer";
/// {id: number, status: number, headers: Record<string,string>} — Response head arrived.
pub const EV_FETCH_STATUS: &str = "fetchStatus";
/// {id: number, text: string} — A body chunk (UTF-8 text, lossy on invalid bytes; v1 is text-only).
pub const EV_FETCH_CHUNK: &str = "fetchChunk";
/// {id: number} — Body finished cleanly.
pub const EV_FETCH_DONE: &str = "fetchDone";
/// {id: number, message: string, aborted: boolean} — Request failed or was aborted.
pub const EV_FETCH_ERROR: &str = "fetchError";

pub const OP_NAMES: &[&str] = &["now", "monotonic", "random", "timerStart", "timerClear", "fetchStart", "fetchAbort", "fsRead", "fsWrite", "fsAppend", "fsExists", "fsRemove", "env", "args", "exit"];
pub const EVENT_NAMES: &[&str] = &["timer", "fetchStatus", "fetchChunk", "fetchDone", "fetchError"];
