// Codegen: spec/spec.ts -> host/src/spec_generated.rs (the PocketJS
// spec-pinning pattern). Run: node spec/codegen.mjs [--check]
// --check exits 1 if the committed file differs (the CI drift guard).
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const specSource = readFileSync(join(here, "spec.ts"), "utf8")

// spec.ts is data; evaluate the literals without a TS toolchain.
const pick = (name) => {
  const m = specSource.match(new RegExp(`export const ${name}[^=]*=\\s*(\\[[\\s\\S]*?\\])\\s*as const`))
  if (!m) throw new Error(`spec.ts: cannot find ${name}`)
  return eval(m[1])
}
const OPS = pick("OPS")
const EVENTS = pick("EVENTS")
const VERSION = Number(specSource.match(/export const VERSION = (\d+)/)[1])

const rust = `// AUTO-GENERATED by spec/codegen.mjs from spec/spec.ts — DO NOT EDIT.
// The \`pi\` surface, pinned. Codes are append-only (RUNTIMES.md).

#![allow(dead_code)]

pub const SURFACE: &str = "pi";
pub const VERSION: u32 = ${VERSION};
pub const DISPATCH: &str = "__pi_dispatch";

${OPS.map((op) => `/// ${op.sig} — ${op.doc}\npub const OP_${op.name.replace(/[A-Z]/g, (c) => "_" + c).toUpperCase()}: u32 = ${op.code};`).join("\n")}

${EVENTS.map((ev) => `/// ${ev.fields} — ${ev.doc}\npub const EV_${ev.name.replace(/[A-Z]/g, (c) => "_" + c).toUpperCase()}: &str = "${ev.name}";`).join("\n")}

pub const OP_NAMES: &[&str] = &[${OPS.map((op) => `"${op.name}"`).join(", ")}];
pub const EVENT_NAMES: &[&str] = &[${EVENTS.map((ev) => `"${ev.name}"`).join(", ")}];
`

const out = join(here, "..", "host", "src", "spec_generated.rs")
if (process.argv.includes("--check")) {
  const committed = readFileSync(out, "utf8")
  if (committed !== rust) {
    console.error("spec drift: host/src/spec_generated.rs is stale — run `node spec/codegen.mjs`")
    process.exit(1)
  }
  console.log("spec: no drift")
} else {
  writeFileSync(out, rust)
  console.log(`wrote ${out}`)
}
