#!/usr/bin/env node
// Regenerate stage/src/assets.rs from the English-named sprite PNGs in
// stage/assets/. Frames are grouped by filename prefix (`<group>_<n>.png`)
// and embedded at compile time via include_bytes!. Node only — no bun.
//
//   node stage/gen-assets.mjs
import { readdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const dir = join(here, "assets")

const groups = {}
for (const f of readdirSync(dir).filter((f) => f.endsWith(".png"))) {
  const m = f.match(/^([a-z]+)_(\d+)\.png$/)
  if (!m) continue
  ;(groups[m[1]] ??= [])[Number(m[2])] = f
}

let rs = "// AUTO-GENERATED by gen-assets.mjs from stage/assets/*.png — DO NOT EDIT.\n"
rs += "pub struct Group{pub name:&'static str,pub frames:&'static [&'static [u8]]}\n"
rs += "pub const GROUPS:&[Group]=&[\n"
for (const g of Object.keys(groups).sort()) {
  const embeds = groups[g].map((f) => `include_bytes!("../assets/${f}")`).join(",")
  rs += `  Group{name:"${g}",frames:&[${embeds}]},\n`
}
rs += "];\n"
writeFileSync(join(here, "src", "assets.rs"), rs)
console.log("assets:", Object.entries(groups).map(([k, v]) => `${k}:${v.length}`).join(" "))
