#!/usr/bin/env node
// Populate stage/assets/*.png + stage/src/assets.rs from the Pocket Cat
// sprite sheets. The art is the user's (dozycat-io/design) and is NOT
// committed to this public repo — run this before `cargo build`.
//
//   node stage/gen-assets.mjs [--design <dir>]
//
// Default design dir: ../dozycat-io/design relative to the pocket-pi repo
// root (i.e. a sibling checkout). Node only — no bun, no python.
import { readdirSync, copyFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const argi = process.argv.indexOf("--design")
const design = argi >= 0 ? process.argv[argi + 1] : join(here, "..", "..", "dozycat-io", "design")
const cats = join(design, "猫猫")
const bubbles = join(design, "对话框和红心等")

if (!existsSync(cats)) {
  console.error(`design dir not found: ${design}\n` +
    `pass --design <dir> pointing at dozycat-io/design (the sprite sheets).`)
  process.exit(1)
}

const out = join(here, "assets")
mkdirSync(out, { recursive: true })

// group -> ordered list of source files (relative to design/)
const plan = {
  idle: ["猫猫/待机/idlestate.png"],
  work: Array.from({ length: 10 }, (_, i) => `猫猫/工作/workstate${i + 1}.png`),
  talk: [1, 2, 3].map((i) => `猫猫/说话/talkstate${i}.png`),
  sleep: [1, 5, 10, 15].map((i) => `猫猫/睡觉/sleepstate${i}.png`),
  excited: Array.from({ length: 8 }, (_, i) => `猫猫/兴奋/runstate${i + 1}.png`),
  jump: [1, 2].map((i) => `猫猫/跳/jumpstate${i}.png`),
  heart: ["对话框和红心等/小对话框和红心/red01.png", "对话框和红心等/小对话框和红心/red02.png"],
  zzz: ["对话框和红心等/zzz/zzz-a1.png", "对话框和红心等/zzz/zzz-a2.png", "对话框和红心等/zzz/zzz-a3.png"],
}

let rs = "// AUTO-GENERATED by gen-assets.mjs — sprite groups embedded at compile time.\n"
rs += "pub struct Group{pub name:&'static str,pub frames:&'static [&'static [u8]]}\n"
rs += "pub const GROUPS:&[Group]=&[\n"
for (const [group, files] of Object.entries(plan)) {
  const embeds = files.map((rel, i) => {
    const dst = `${group}_${i}.png`
    copyFileSync(join(design, rel), join(out, dst))
    return `include_bytes!("../assets/${dst}")`
  })
  rs += `  Group{name:"${group}",frames:&[${embeds.join(",")}]},\n`
}
rs += "];\n"
writeFileSync(join(here, "src", "assets.rs"), rs)
console.log(`assets: ${Object.entries(plan).map(([k, v]) => k + ":" + v.length).join(" ")} → stage/assets + src/assets.rs`)
